repos:
-   repo: local
    hooks:
    # Removed the local build hook as builds are now handled by GitHub Actions
    # -   id: build-appimage
    #     name: Build AppImage/EXE (Linux/Windows)
    #     entry: scripts/build_appimage.sh
    #     language: script
    #     always_run: true
    #     pass_filenames: false
    #     verbose: true # Show output from the script
    -   id: pytype
        name: Python Type Checker (pytype)
        entry: scripts/run_pytype.sh
        language: script
        types: [python]
        pass_filenames: false 